amund_io/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from .views import Index, About

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tags/', include('tags.urls')),
    url(r'^files/', include('files.urls')),
    url(r'^article/', include('articles.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^numclass/', include('numclass.urls')),
    url(r'^astar/', include('astar.urls')),
    url(r'^about/', About.as_view()),
    url(r'^$', Index.as_view()),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

astar/urls.py
from django.conf.urls import url
from django.contrib import admin

from astar.views import Index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Index.as_view()),
]

tags/urls.py
from django.conf.urls import url
from .views import edit, new, delete, name

urlpatterns = [
    url(r'^edit/$', edit, name='edit'),
    url(r'^edit/name/(?P<name>.*)/$', name, name='edit-name'),
    url(r'^(?P<group_id>[0-9]+)/edit/$', edit, name='edit'),
    url(r'^delete/(?P<tag_id>[0-9]+)/$', delete, name='delete'),
    url(r'^(?P<group_id>[0-9]+)/edit/new/$', new, name='new'),
]

tags/models.py
from django.db import models
from django.utils import timezone


class TagGroup(models.Model):
    title = models.CharField(max_length=100, unique=True, verbose_name='Title')
    creation_date = models.DateTimeField(default=timezone.now, verbose_name='Creation Date')

    def __str__(self):
        return self.title


class Tag(models.Model):
    label = models.CharField(max_length=100, verbose_name='Label')
    group = models.ForeignKey(TagGroup, verbose_name='Group', on_delete=models.SET_NULL, null=True)
    creation_date = models.DateTimeField(default=timezone.now, verbose_name='Creation Date')

    class Meta:
        permissions = (
            ("view_tag_control_panel", "Can view tag control panel"),
        )
        unique_together = ('label', 'group')

    def __str__(self):
        return self.label

    @staticmethod
    def clean_tags(tags):
        cleaned = []
        for tag in tags.split(','):
            try:
                cleaned.append(int(tag.strip()))
            except ValueError:
                pass
        return cleaned

    @staticmethod
    def stringlist(manager):
        tags = manager.all()
        return ', '.join([tag.label for tag in tags])

tags/views.py
from django.db import IntegrityError
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.contrib.auth.decorators import permission_required

from .models import Tag, TagGroup

@permission_required('tags.view_tag_control_panel')
def edit(request, group_id=0):
    group_id = int(group_id)

    context = {
        'groups': TagGroup.objects.all()
    }

    if group_id > 0:
        try:
            context['group'] = TagGroup.objects.get(pk=group_id)
            context['tags'] = context['group'].tag_set.all().order_by('label')
        except TagGroup.DoesNotExist:
            return HttpResponseRedirect('/tags/edit/')

    return render(request, 'tags/edit.html', context)

@permission_required('tags.add_tag')
def new(request, group_id):
    group_id = int(group_id)

    try:
        group = TagGroup.objects.get(pk=group_id)
    except (TagGroup.DoesNotExist):
        return JsonResponse({
            'success': False,
            'error': 'Unable to find category'
        })

    if 'tag' in request.POST and request.POST['tag']:
        label = request.POST['tag'].strip().lower()
        try:
            tag = Tag.objects.create(label=label, group=group)
            return JsonResponse({
                'success': True,
                'pk': tag.id,
            })
        except IntegrityError:
            return JsonResponse({
                'success': False,
                'error': 'Tag already exists',
            })
    else:
        return JsonResponse({
            'success': False,
            'error': 'Tag cannot be empty'
        })

@permission_required('tags.delete_tag')
def delete(request, tag_id):
    tag_id = int(tag_id)
    try:
        tag = Tag.objects.get(pk=tag_id)
        tag.delete()
        return JsonResponse({
            'success': True,
        })
    except Tag.DoesNotExist:
        return JsonResponse({
            'success': False,
            'error': 'Cannot delete nonexisting tag',
        })

@permission_required('tags.view_tag_control_panel')
def name(request, name):
    try:
        group = TagGroup.objects.get(title=name)
        return HttpResponseRedirect('/tags/%r/edit/' % group.id)
    except TagGroup.DoesNotExist:
        return HttpResponseRedirect('/tags/edit/')

tags/templates/tags/edit.html
{% extends 'amund_io/base.html' %}
{% load staticfiles %}

{% block title %}
Edit tags
{% endblock title %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static "tags/css/edit.css" %}">
{% endblock head %}

{% block content %}

  <div class="ui middle aligned center aligned grid">
    <div class="column">
      <h2 class="ui header blue">
        Manage tags
      </h2>
      <div class="ui segment">

        <div class="ui inline field">
          <label for="id_group" id="grouplabel">Category</label>
          <div class="ui selection dropdown search scrolling field group">
            <input id="id_group" class="dummy" name="group" type="hidden">
            <i class="dropdown icon"></i>
            <div class="default text">Group</div>
            <div class="menu">
              {% for group in groups %}
                <a class="item" href="/tags/{{ group.id }}/edit">{{ group.title|title }}</a>
              {% endfor %}
            </div>
          </div>
        </div>

        <div class="tags">
          {% for tag in tags %}
            <a class="ui label blue">
              {{ tag }}<i class="delete icon delete ajax" pk="{{ tag.id }}"></i>
            </a>
          {% endfor %}
        </div>

        {% if group %}
          <div class="ui form">
            <div class="ui inline field add">
              <input class="newtag" type="text" name="tag">
              <div class="ui fluid submit button blue">Add</div>
            </div>
          </div>
        {% endif %}

      </div>
    </div>
  </div>

  <script src="{% static "tags/js/edit.js" %}"></script>
  <script>
    {% if group %}
      $('.group.dropdown').dropdown('set exactly', '{{ group.title|title }}');
    {% else %}
      $('.group.dropdown').dropdown();
    {% endif %}

    csrf_token = '{{ csrf_token }}';
  </script>
{% endblock content %}